import type { PresetPalette } from './types'

export const presetPalettes: PresetPalette[] = [
  {
    name: 'Main site',
    colors: {
      plain: {
        bg: '#ffffff',
        'bg-secondary': '#f4f4f6',
        text: '#1e1d25',
        'text-secondary': '#4e4c62',
        'text-accent': '#eb2a2f',
        'text-link': '#2805ff',
        'action-primary': '#2805ff',
        'action-primary-text': '#ffffff',
        'action-secondary': '#2805ff',
        'action-secondary-text': '#2805ff',
        'action-primary-hover': '#1e00d4',
        'action-primary-active': '#150093',
        'action-secondary-hover': 'hsla(248, 100%, 51%, 0.102)',
        'action-secondary-active': 'hsla(248, 100%, 51%, 0.302)',
        'input-bg': '#eeeef1',
      },
      tint: {
        bg: '#fff6f6',
        'bg-secondary': '#f7ecec',
        text: '#1e1d25',
        'text-secondary': '#9c5557',
        'text-accent': '#cc5d60',
        'text-link': '#2805ff',
        'action-primary': '#440000',
        'action-primary-text': '#fdfdfd',
        'action-secondary': '#440000',
        'action-secondary-text': '#440000',
        'action-primary-hover': '#643637',
        'action-primary-active': '#3f2021',
        'action-secondary-hover': 'hsla(0, 52%, 37%, 0.102)',
        'action-secondary-active': 'hsla(0, 52%, 37%, 0.2)',
        'input-bg': '#f5cdce',
      },
      general: {
        'card-border': 'rgba(0, 0, 0, 0.1)',
        'card-shadow': '0 5px 40px #0000001a, inset 0 2px 0 -1px #ffffff80',
      },
    },
  },
  {
    name: 'Archive',
    colors: {
      plain: {
        bg: '#ffffff',
        'bg-secondary': '#f4f4f6',
        text: '#000000',
        'text-secondary': '#484848',
        'text-accent': '#d4213a',
        'text-link': '#2805ff',
        'action-primary': '#000000',
        'action-primary-text': '#ffffff',
        'action-secondary': '#000000',
        'action-secondary-text': '#000000',
        'action-primary-hover': '#3a3a3a',
        'action-primary-active': '#636363',
        'action-secondary-hover': '#0000001a',
        'action-secondary-active': '#0000004d',
        'input-bg': '#eeeef1',
      },
      tint: {
        bg: '#ffedec',
        'bg-secondary': '#f7dedd',
        text: '#310206',
        'text-secondary': '#861021',
        'text-accent': '#d4213a',
        'text-link': '#2805ff',
        'action-primary': '#d4213a',
        'action-primary-text': '#fdfdfd',
        'action-secondary': '#d4213a',
        'action-secondary-text': '#d4213a',
        'action-primary-hover': '#b61a30',
        'action-primary-active': '#861021',
        'action-secondary-hover': '#d4213a1a',
        'action-secondary-active': '#d4213a33',
        'input-bg': '#ffd6d4',
      },
      general: {
        'card-border': 'rgba(0, 0, 0, 0.1)',
        'card-shadow': '0 5px 40px #0000001a, inset 0 2px 0 -1px #ffffff80',
      },
    },
    dark: {
      plain: {
        bg: '#150e0e',
        'bg-secondary': '#241d1d',
        text: '#ffffff',
        'text-secondary': '#d6d6d6',
        'text-accent': '#f22643',
        'text-link': '#2805ff',
        'action-primary': '#ffffff',
        'action-primary-text': '#000000',
        'action-secondary': '#ffffff',
        'action-secondary-text': '#ffffff',
        'action-primary-hover': '#dedede',
        'action-primary-active': '#aeaeae',
        'action-secondary-hover': '#ffffff1a',
        'action-secondary-active': '#ffffff4d',
        'input-bg': '#2c2c2c',
      },
      tint: {
        bg: '#3f1516',
        'bg-secondary': '#4e2525',
        text: '#ffffff',
        'text-secondary': '#fcbbb8',
        'text-accent': '#f94b57',
        'text-link': '#2805ff',
        'action-primary': '#d4213a',
        'action-primary-text': '#fdfdfd',
        'action-secondary': '#fdd4d2',
        'action-secondary-text': '#fdd4d2',
        'action-primary-hover': '#ee2542',
        'action-primary-active': '#f94b57',
        'action-secondary-hover': '#fdd4d21a',
        'action-secondary-active': '#fdd4d233',
        'input-bg': '#602426',
      },
      general: {
        'card-border': 'rgba(255, 255, 255, 0.3)',
        'card-shadow': '0 5px 40px #000000a4, inset 0 2px 0 -1px #ffffff60',
      },
    },
  },
  {
    name: 'Pretends to be Drawing',
    colors: {
      plain: {
        bg: '#ffffff',
        'bg-secondary': '#f4f4f6',
        text: '#1e1d25',
        'text-secondary': '#4e4c62',
        'text-accent': '#ff543c',
        'text-link': '#2805ff',
        'action-primary': '#271614',
        'action-primary-text': '#fdfdfd',
        'action-primary-hover': '#793128',
        'action-primary-active': '#a94235',
        'action-secondary': '#271614',
        'action-secondary-text': '#271614',
        'action-secondary-hover': '#ffb4aa40',
        'action-secondary-active': '#ffb4aabf',
        'input-bg': '#eeeef1',
      },
      tint: {
        bg: '#fff8f5',
        'bg-secondary': '#f8ebe6',
        text: '#c31902',
        'text-secondary': '#9c5557',
        'text-accent': '#ff543c',
        'text-link': '#2805ff',
        'action-primary': '#271614',
        'action-primary-text': '#fdfdfd',
        'action-primary-hover': '#793128',
        'action-primary-active': '#a94235',
        'action-secondary': '#271614',
        'action-secondary-text': '#271614',
        'action-secondary-hover': '#ffb4aa40',
        'action-secondary-active': '#ffb4aabf',
        'input-bg': '#f5cdce',
      },
      general: {
        'card-border': 'rgba(0, 0, 0, 0.1)',
        'card-shadow': '0 5px 40px #0000001a, inset 0 2px 0 -1px #ffffff80',
      },
    },
    dark: {
      plain: {
        bg: '#0f0f0f',
        'bg-secondary': '#1d1d1d',
        text: '#ffe6e2',
        'text-secondary': '#d86d5c',
        'text-accent': '#ff543c',
        'text-link': '#68e4ff',
        'action-primary': '#ffb4aa',
        'action-primary-text': '#c54d3c',
        'action-primary-hover': '#de8679',
        'action-primary-active': '#a94235',
        'action-secondary': '#ffb4aa',
        'action-secondary-text': '#ffb4aa',
        'action-secondary-hover': '#ffb4aa40',
        'action-secondary-active': '#ffb4aabf',
        'input-bg': '#271614',
      },
      tint: {
        bg: '#271614',
        'bg-secondary': '#372321',
        text: '#ec8172',
        'text-secondary': '#c85b4d',
        'text-accent': '#ff543c',
        'text-link': '#68e4ff',
        'action-primary': '#ffb4aa',
        'action-primary-text': '#c54d3c',
        'action-primary-hover': '#de8679',
        'action-primary-active': '#a94235',
        'action-secondary': '#ffb4aa',
        'action-secondary-text': '#ffb4aa',
        'action-secondary-hover': '#ffb4aa40',
        'action-secondary-active': '#ffb4aabf',
        'input-bg': '#0f0f0f',
      },
      general: {
        'card-border': 'rgba(255, 255, 255, 0.1)',
        'card-shadow': '0 5px 40px #0000008a, inset 0 2px 0 -1px #ffffff80',
      },
    },
  },
  {
    name: 'Tabby',
    colors: {
      plain: {
        bg: '#ffffff',
        'bg-secondary': '#f4f4f6',
        text: '#1e1d25',
        'text-secondary': '#4e4c62',
        'text-accent': '#eb2a2f',
        'text-link': '#2805ff',
        'action-primary': '#0a84ff',
        'action-primary-text': '#fdfdfd',
        'action-primary-hover': '#0072e5',
        'action-primary-active': '#0066cc',
        'action-secondary': '#0a84ff',
        'action-secondary-text': '#0a84ff',
        'action-secondary-hover': '#3d3f4c1a',
        'action-secondary-active': '#3d3f4c33',
        'input-bg': '#eeeef1',
      },
      tint: {
        bg: '#fff6f6',
        'bg-secondary': '#f7ecec',
        text: '#1e1d25',
        'text-secondary': '#713032',
        'text-accent': '#cc5d60',
        'text-link': '#2805ff',
        'action-primary': '#bd5673',
        'action-primary-text': '#fdfdfd',
        'action-primary-hover': '#643637',
        'action-primary-active': '#3f2021',
        'action-secondary': '#bd5673',
        'action-secondary-text': '#bd5673',
        'action-secondary-hover': '#8f2d2d1a',
        'action-secondary-active': '#8f2d2d33',
        'input-bg': '#f5cdce',
      },
      general: {
        'card-border': 'rgba(0, 0, 0, 0.1)',
        'card-shadow': '0 5px 40px #0000001a, inset 0 2px 0 -1px #ffffff80',
      },
    },
    dark: {
      plain: {
        bg: '#121212',
        'bg-secondary': '#1f1f23',
        text: '#eeecfc',
        'text-secondary': '#9391aa',
        'text-accent': '#fa5e88',
        'text-link': '#8fd0ff',
        'action-primary': '#c3bbf4',
        'action-primary-text': '#000000',
        'action-primary-hover': '#7b73ae',
        'action-primary-active': '#564e86',
        'action-secondary': '#c3bbf4',
        'action-secondary-text': '#c3bbf4',
        'action-secondary-hover': '#c3bbf41a',
        'action-secondary-active': '#c3bbf433',
        'input-bg': '#1f1f26',
      },
      tint: {
        bg: '#251316',
        'bg-secondary': '#352124',
        text: '#fddfe4',
        'text-secondary': '#db8a98',
        'text-accent': '#fa5e88',
        'text-link': '#8fd0ff',
        'action-primary': '#f48faa',
        'action-primary-text': '#321015',
        'action-primary-hover': '#c95876',
        'action-primary-active': '#89344a',
        'action-secondary': '#f48faa',
        'action-secondary-text': '#f48faa',
        'action-secondary-hover': '#f48faa30',
        'action-secondary-active': '#f48faa60',
        'input-bg': '#3c1b22',
      },
      general: {
        'card-border': 'rgba(255, 255, 255, 0.2)',
        'card-shadow': '0 5px 40px #00000070',
      },
    },
  },
]
